export {default as Header} from './Header'
export {default as Hero} from './Hero'
export {default as CustomButton} from './CustomButton'
export {default as Partner} from './Partner'
export {default as HeroText} from './HeroText'